name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: How would this benefit users?
